-- ========================================================================= --
--                                                                           --
-- Copyright (c) 2014 Matt Fichman <matt.fichman@gmail.com>                  --
--                                                                           --
-- This file is part of Quadrant. It is subject to the license terms in the  --
-- LICENSE file found in the top-level directory of this software package,   --
-- No part of Quadrant, including this file, may be copied, modified,        --
-- propagated, or distributed except according to the terms contained in the --
-- LICENSE file.                                                             --
--                                                                           --
-- ========================================================================= --
