-- Copyright (c) 2014 Matt Fichman
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to
-- deal in the Software without restriction, including without limitation the
-- rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
-- sell copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
-- 
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
-- 
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
-- FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
-- IN THE SOFTWARE.

local sfml = require('sfml')

return {
  ['a']=sfml.KeyA,            
  ['b']=sfml.KeyB,            
  ['c']=sfml.KeyC,            
  ['d']=sfml.KeyD,            
  ['e']=sfml.KeyE,            
  ['f']=sfml.KeyF,            
  ['g']=sfml.KeyG,            
  ['h']=sfml.KeyH,            
  ['i']=sfml.KeyI,            
  ['j']=sfml.KeyJ,            
  ['k']=sfml.KeyK,            
  ['l']=sfml.KeyL,            
  ['m']=sfml.KeyM,            
  ['n']=sfml.KeyN,            
  ['o']=sfml.KeyO,            
  ['p']=sfml.KeyP,            
  ['q']=sfml.KeyQ,            
  ['r']=sfml.KeyR,            
  ['s']=sfml.KeyS,            
  ['t']=sfml.KeyT,            
  ['u']=sfml.KeyU,            
  ['v']=sfml.KeyV,            
  ['w']=sfml.KeyW,            
  ['x']=sfml.KeyX,            
  ['y']=sfml.KeyY,            
  ['z']=sfml.KeyZ,            
  ['num0']=sfml.KeyNum0,         
  ['num1']=sfml.KeyNum1,         
  ['num2']=sfml.KeyNum2,         
  ['num3']=sfml.KeyNum3,         
  ['num4']=sfml.KeyNum4,         
  ['num5']=sfml.KeyNum5,         
  ['num6']=sfml.KeyNum6,         
  ['num7']=sfml.KeyNum7,         
  ['num8']=sfml.KeyNum8,         
  ['num9']=sfml.KeyNum9,         
  ['escape']=sfml.KeyEscape,       
  ['lcontrol']=sfml.KeyLControl,     
  ['lshift']=sfml.KeyLShift,       
  ['lalt']=sfml.KeyLAlt,         
  ['lsystem']=sfml.KeyLSystem,      
  ['rcontrol']=sfml.KeyRControl,     
  ['rshift']=sfml.KeyRShift,       
  ['ralt']=sfml.KeyRAlt,         
  ['rsystem']=sfml.KeyRSystem,      
  ['menu']=sfml.KeyMenu,         
  ['lbracket']=sfml.KeyLBracket,     
  ['rbracket']=sfml.KeyRBracket,     
  ['semicolon']=sfml.KeySemiColon,    
  ['comma']=sfml.KeyComma,        
  ['period']=sfml.KeyPeriod,       
  ['quote']=sfml.KeyQuote,        
  ['slash']=sfml.KeySlash,        
  ['backslash']=sfml.KeyBackSlash,    
  ['tilde']=sfml.KeyTilde,        
  ['equal']=sfml.KeyEqual,        
  ['dash']=sfml.KeyDash,         
  ['space']=sfml.KeySpace,        
  ['return']=sfml.KeyReturn,       
  ['back']=sfml.KeyBack,         
  ['tab']=sfml.KeyTab,          
  ['pageup']=sfml.KeyPageUp,       
  ['pagedown']=sfml.KeyPageDown,     
  ['end']=sfml.KeyEnd,          
  ['home']=sfml.KeyHome,         
  ['insert']=sfml.KeyInsert,       
  ['delete']=sfml.KeyDelete,       
  ['add']=sfml.KeyAdd,          
  ['subtract']=sfml.KeySubtract,     
  ['multiply']=sfml.KeyMultiply,     
  ['divide']=sfml.KeyDivide,       
  ['left']=sfml.KeyLeft,         
  ['right']=sfml.KeyRight,        
  ['up']=sfml.KeyUp,           
  ['down']=sfml.KeyDown,         
  ['numpad0']=sfml.KeyNumpad0,      
  ['numpad1']=sfml.KeyNumpad1,      
  ['numpad2']=sfml.KeyNumpad2,      
  ['numpad3']=sfml.KeyNumpad3,      
  ['numpad4']=sfml.KeyNumpad4,      
  ['numpad5']=sfml.KeyNumpad5,      
  ['numpad6']=sfml.KeyNumpad6,      
  ['numpad7']=sfml.KeyNumpad7,      
  ['numpad8']=sfml.KeyNumpad8,      
  ['numpad9']=sfml.KeyNumpad9,      
  ['f1']=sfml.KeyF1,           
  ['f2']=sfml.KeyF2,           
  ['f3']=sfml.KeyF3,           
  ['f4']=sfml.KeyF4,           
  ['f5']=sfml.KeyF5,           
  ['f6']=sfml.KeyF6,           
  ['f7']=sfml.KeyF7,           
  ['f8']=sfml.KeyF8,           
  ['f9']=sfml.KeyF9,           
  ['f10']=sfml.KeyF10,          
  ['f11']=sfml.KeyF11,          
  ['f12']=sfml.KeyF12,          
  ['f13']=sfml.KeyF13,          
  ['f14']=sfml.KeyF14,          
  ['f15']=sfml.KeyF15,          
  ['pause']=sfml.KeyPause,        
}

